package app.services;

import java.util.List;

import org.javalite.activeweb.DBSpec;
import org.junit.Test;

import app.entity.AmazonItem;

public class AmazonCrawlerServiceTest extends DBSpec {

	@Test
	public void test_type() throws Exception {
		a(AmazonCrawlerService.class).shouldNotBeNull();
	}

	@Test
	public void test_instantiation() throws Exception {
		AmazonCrawlerService target = new AmazonCrawlerService();
		a(target).shouldNotBeNull();
	}


	@Test
	public void test_searchItem_A$String$String$Integer$Integer() throws Exception {
		// Arrange
		AmazonCrawlerService service = new AmazonCrawlerService();
		String searchIndex = "DVD";
		String browseNode = "16295841";
		Integer itemPage = 1;
		Integer minimumPrice = 5000;
		
		// Act
		List<AmazonItem> items = service.searchItem(searchIndex, browseNode, itemPage, minimumPrice);
		
		// Assert
		a(items.size()).shouldBeEqual(10);
	}

	@Test
	public void test_execute_A$() throws Exception {
		AmazonCrawlerService target = new AmazonCrawlerService();
		target.execute();
	}

	@Test
	public void test_lookupItem_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		AmazonCrawlerService target = new AmazonCrawlerService();
		List<AmazonItem> actual = target.lookupItem();
		List<AmazonItem> expected = null;
	
	}

}
