package app.services;

import app.services.YahooAuctionService.*;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.javalite.http.Get;
import org.javalite.http.Http;
import org.json.simple.parser.ParseException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import app.dto.YahooAuctionItem;
import app.system.AbstractBaseService;
import junit.framework.TestCase;

public class YahooAuctionServiceTest extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(YahooAuctionService.class);
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		YahooAuctionService target = new YahooAuctionService();
		assertNotNull(target);
	}


	public void test_extractKeyphrase_A$String() throws Exception {
		// TODO auto-generated by JUnit Helper.
		YahooAuctionService target = new YahooAuctionService();
		String text = "せどり初心者は中古と新品ではどちらが向いているか？";
		List<String> actual = target.extractKeyphrase(text);
		List<String> expected = null;
		assertEquals(expected, actual);
	}





}
